name: nextjs-cloud-run

on:
  push:
    branches:
      - master
      - main

env:
  CLOUD_RUN_PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  CLOUD_RUN_REGION: asia-northeast1
  REPO_NAME: nextjs-website # project-name

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
        service_account_key: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}
        service_account_email: cicd-561@nextjs-test02.iam.gserviceaccount.com

    - run: |-
        gcloud services enable containerregistry.googleapis.com
        gcloud services enable run.googleapis.com
        gcloud --quiet auth configure-docker

    - name: Build and tag image
      run: |-
        docker build . --tag "gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA"

    - name: Push image to GCR
      run: |-
        docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA

    - name: Deploy
      run: |-
        gcloud beta run deploy $REPO_NAME --image gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
          --project $CLOUD_RUN_PROJECT_ID \
          --platform managed \
          --region $CLOUD_RUN_REGION \
          --allow-unauthenticated \
          --quiet
